import { GoogleGenAI, Type } from "@google/genai";
import { BioExercise } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

// Schema for the exercise text generation
const exerciseSchema = {
  type: Type.OBJECT,
  properties: {
    title: { type: Type.STRING, description: "Name of the bioenergetic exercise" },
    description: { type: Type.STRING, description: "A brief, encouraging summary of what the exercise involves" },
    instructions: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: "Step-by-step instructions (max 5 steps)",
    },
    benefits: { type: Type.STRING, description: "Explanation of why this is good for the body/mind" },
    imagePrompt: { type: Type.STRING, description: "A descriptive prompt to generate an illustration of a person performing this exercise. Minimalist, clean line art or flat style." },
  },
  required: ["title", "description", "instructions", "benefits", "imagePrompt"],
};

export const generateBioExercise = async (): Promise<BioExercise> => {
  // 1. Generate the Text Content
  const textResponse = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: "Generate a unique, simple, and effective bioenergetic exercise for today. It should focus on grounding, breathing, or releasing tension. The tone should be calming and professional.",
    config: {
      responseMimeType: "application/json",
      responseSchema: exerciseSchema,
      systemInstruction: "You are an expert Bioenergetic Therapist. Create safe, effective daily exercises.",
    },
  });

  const exerciseData = JSON.parse(textResponse.text || "{}");

  // 2. Generate the Image based on the prompt
  // We use the prompt generated by the first model to ensure consistency
  let imageBase64 = "";
  try {
    const imageResponse = await ai.models.generateContent({
      model: "gemini-2.5-flash-image",
      contents: {
        parts: [
          { text: `A clean, modern, flat vector style illustration of a person doing this exercise: ${exerciseData.imagePrompt}. Soft pastel colors, white background, high quality.` }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1" // Square for card layout
        }
      }
    });

    // Extract image
    for (const part of imageResponse.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
            imageBase64 = part.inlineData.data;
            break;
        }
    }
  } catch (error) {
    console.error("Failed to generate image:", error);
    // We will gracefully handle missing image in UI
  }

  return {
    id: Date.now().toString(),
    ...exerciseData,
    imageBase64: imageBase64,
  };
};